# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200307_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photos',
            field=models.ImageField(default='photo', upload_to='img'),
        ),
    ]
