# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-20 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20200307_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lat',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='lng',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
