# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-20 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20200320_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lng',
        ),
    ]
