# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-20 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20200320_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lat',
            field=models.CharField(default='Latitude', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='lng',
            field=models.CharField(default='Longitude', max_length=20),
        ),
    ]
