# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-22 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_auto_20200321_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='buy',
            new_name='sale',
        ),
    ]
