# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('street_address1', models.CharField(max_length=40)),
                ('street_address2', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField()),
            ],
        ),
    ]
