# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_signup_name'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Payment')),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Signup')),
            ],
        ),
    ]
