# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-23 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
