# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
