# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_package', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy_Package',
        ),
    ]
